# UAT Environment Configuration

environment: uat

image:
  repository: myapp
  tag: 1.0.0
  pullPolicy: Always

replicas: 2

cluster:
  name: uat-cluster
  region: us-west-2

database:
  host: db.uat.example.com
  port: 5432

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
